# wrangler.toml
name = "shopify-partners-slack-noti"
main = "src/index.js"
workers_dev = true
compatibility_date = "2023-09-22"

[triggers]
  crons = ["*/10 * * * *"]  # This cron job will run every 10 minutes
